name: semantic-release

on:
  push:
    branches: [main]

jobs:
  tests-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Run tests & lint
        run: |
          yarn install --frozen-lockfile
          yarn release