name: semantic-release

on:
  push:
    branches: [main]

jobs:
  install-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Run install and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn install --frozen-lockfile
          yarn release